Feat/letters
rHomelab/LabBot-Cogs pull request #161
Opened 2021-07-15 17:46 UTC by tigattack

# Initial Checklist
- [x] Has @tigattack / @kdavis / @issy been added as a reviewer?
- [x] If applicable, have the relevant project(s), milestone(s), and label(s) been applied?
- [x] If applicable, have you added details of the cog to the readme as per [README.md](https://github.com/rHomelab/LabBot-Cogs/blob/develop/README.md#cog-summaries)?

# Details
* **Does this resolve an issue?**
Resolves #160

## Changes
### New Features
* Add limited support for special characters (!?#'.).
* Add `-raw` flag to output emote code in code block.
* Limit output length to 2000 characters.

### Breaking Changes
N/A.

## Additional
N/A.

2021-07-15 22:38 UTC, kdavis requested changes
Really proud of your first cog x

2021-07-15 22:38 UTC, kdavis commented on letters/letters.py
> +                letters += f"{specials[str(char)]}"
String interpolation isn't needed here

2021-07-15 22:38 UTC, kdavis commented on letters/letters.py
> +            output = f"{letters}"
String interpolation isn't needed here

2021-07-15 22:38 UTC, kdavis commented on letters/letters.py
> +        else:
This else could be simplified to instantiating `raw` as False above the if statement

2021-07-15 23:32 UTC, tigattack commented on letters/letters.py
> +        return specials[char]
This needs to be changed back to use string interpolation with a space at the end, matching lines 21 and 25.

2021-07-15 23:35 UTC, issy approved these changes
With punctuation spacing now fixed I think this is merge-ready

2021-07-16 09:06 UTC, issy approved these changes

2021-07-16 09:24 UTC, merged