Custom message cog
rHomelab/LabBot-Cogs pull request #182
Opened 2021-10-02 21:42 UTC by issy

# Initial Checklist
- [x] Has @tigattack / @issy been added as a reviewer?
- [x] If applicable, have the relevant project(s), milestone(s), and label(s) been applied?
- [ ] If applicable, have you added details of the cog to the readme as per [README.md](https://github.com/rHomelab/LabBot-Cogs/blob/develop/README.md#cog-summaries)?

# Details

This PR adds an interactive message builder for moderators to send messages using the bot.
This can be seen in action here.
![image](https://user-images.githubusercontent.com/48881813/135732172-88fca58d-baad-464c-9083-f62fe85d505e.png)

![image](https://user-images.githubusercontent.com/48881813/135732178-e358159e-f786-4076-88be-735b4c2a66c1.png)

* **Does this resolve an issue?**
Resolves #181

## Changes
### Features / Fixes
* Adds `[p]msg create` command to send messages using the bot
* Adds `[p]msg edit` command to edit messages sent by the bot

### Breaking Changes
No breaking changes

## Additional
The current `[p]msg edit` implementation will overwrite the unspecified fields. In other words, if you want to edit a message with text and an embed, and you only want to edit the embed, you will have to choose the `both` option and input the current text body, otherwise it will be removed. This was a stylistic choice, and can be removed if there are any disagreements. The benefit of this method is that you can remove elements from a message (content or embed) if you want to.

2021-10-03 12:56 UTC, tigattack commented
A comment on your final note: How about if the cog detected if the message being edited contains both elements and prompt if you wish to remove one. Then, if one is removed, whether you wish to edit the other, else both remain and you are prompted which (or both) to edit.

This is just an idea I had and I'm unsure as to difficulty of implementation. I don't to cause a bunch more work for you if it'd be too much. This already looks awesome and the functionality as-is is fine, just needs to be clear in the docs/help texts.

2021-12-13 09:53 UTC, issy commented
It turns out this last change is a lot of work, but I'm already like halfway through it, so I may as well complete it

2021-12-13 10:11 UTC, tigattack commented
Much appreciated mate 🙏

2021-12-25 23:21 UTC, issy commented
Ready for review again
![image](https://user-images.githubusercontent.com/48881813/147395352-72f4dd3e-316a-470d-ac6b-77726ddcd995.png)
![image](https://user-images.githubusercontent.com/48881813/147395372-62fae617-2740-422f-a99f-68f7fc05b65a.png)

2021-12-26 00:30 UTC, tigattack requested changes
Amazing, thank you Issy 🙏 As with #191, can't really provide a proper review but what I understand looks ace.

Couple of suggestions for docs/info but otherwise let's goooo.

2021-12-26 00:30 UTC, tigattack commented on README.md
> +  - [Custom msg](#custom-msg)
```suggestion
  - [Custom-msg](#custom-msg)
```

For consistent naming

2021-12-26 00:30 UTC, tigattack commented on custom_msg/info.json
> +    "description": "",
```suggestion
    "short": "Send messages as the bot",
    "description": "Allows moderators to send messages as the bot, also allowing modification of existing messages sent from the cog",

```

Cog short & description.

2021-12-26 13:37 UTC, tigattack approved these changes

2021-12-26 13:39 UTC, merged