Improve convert command
rHomelab/LabBot-Cogs pull request #213
Opened 2022-10-25 13:19 UTC by Darkflame72

# Initial Checklist
- [ ] Has @tigattack / @issy been added as a reviewer?
- [ ] If applicable, have the relevant project(s), milestone(s), and label(s) been applied?
- [ ] If applicable, have you added details of the cog to the readme as per [README.md](https://github.com/rHomelab/LabBot-Cogs/blob/master/README.md#cog-summaries)?

# Details
**Does this resolve an issue?**
Resolves [this](https://discord.com/channels/184315303323238400/281746926662189056/803963156417478718)

## Changes
### Features / Fixes
- moves to using GNU Units for conversion etween units

### Breaking Changes
None

## Additional
Any further notes or comments you want to make.

2022-10-25 17:38 UTC, tigattack commented
Whoops, sorry Issy. Just noticed this is still a draft.

I'll let @Darkflame72 request review when they're ready.

2022-11-07 10:44 UTC, Darkflame72 commented
This now works and is tested and has some slightly prettier error messages. The downside is it relies on GNU utils which must be installed on the system. I would be happy to open a pr to the dockerfile to add it.

2022-11-07 13:02 UTC, tigattack commented
Thanks a lot @Darkflame72!

> I would be happy to open a pr to the dockerfile to add it.

If you wouldn't mind, that would be great.

Please sort the imports to satisfy isort when you get a moment. I'll leave the rest to @issy's superior Python knowledge 😄

2022-11-10 11:57 UTC, Darkflame72 commented
Created the PR for the docker image [here](https://github.com/rHomelab/Red-DiscordBot-Docker/pull/10).

2022-11-10 12:09 UTC, issy requested changes
Just a few minor suggestions. Looks good overall. If you could remove pint from the cog requirements (located in `convert/cog.json`) that would be much appreciated, and feel free to add yourself to the authors list if you want

2022-11-10 12:09 UTC, issy commented on convert/convert.py
> +        self.decimal = re.compile(r"\d+")
let's move `decimal` to global and remove `__init__` altogether

2022-11-10 12:09 UTC, issy commented on convert/convert.py
> +        amount = re.search(self.decimal, arg1).group()
```suggestion
        amount = self.decimal.search(arg1).group()
```
We can use search directly on the pattern

2022-11-10 12:09 UTC, issy commented on convert/convert.py
> +                color=0xFF0000,
```suggestion
                color=discord.Colour.red(),
```

2022-11-10 12:09 UTC, issy commented on convert/convert.py
> +                color=0x00FF00,
```suggestion
                color=discord.Colour.green(),
```

2022-11-10 12:22 UTC, tigattack commented
> feel free to add yourself to the authors list if you want

Good shout, there's also a list of contributors here that you're welcome to add yourself to https://github.com/rHomelab/LabBot-Cogs#other

2022-11-11 17:01 UTC, issy commented
LGTM, thank you

2022-11-11 17:04 UTC, issy approved these changes

2022-11-11 17:31 UTC, merged