feat(verify): add welcome message
rHomelab/LabBot-Cogs pull request #83
Opened 2020-12-05 22:50 UTC by kdavis

# Initial Checklist
- [X] Has @tigattack and/or @kdavis been added as a reviewer?
- [X] If applicable, have the relevant project(s), milestone(s), and label(s) been applied?
- [X] If applicable, have you added details of the cog to the readme as per [README.md](https://github.com/rHomelab/LabBot-Cogs/blob/develop/README.md#cog-summaries)?

# Details
* **Does this resolve an issue?**
Resolves #82 

## Changes
### New Features
* Adds welcome message to a designated channel
* String interpolation on verify message to allow a user mention with `{user}`
* Allows resetting of welcome message by calling `[p]verify welcome`

### Breaking Changes
* N/A

## Additional
* Tidied up verify cog code and removed redundant string interpolations

2020-12-05 23:50 UTC, issy requested changes
I've requested some small tweaks, primarily to the if statement logic, to make it more readable/pythonic. Overall very good job, thank you

2020-12-05 23:50 UTC, issy commented on verify/verify.py
>              if wrongmsg == "":
Empty strings are falsy, this return statement could be more "pythonic"

2020-12-05 23:50 UTC, issy commented on verify/verify.py
>          if role_id is not None:
```suggestion
        if role_id:
```
this is more pythonic and much more readable imo, especially as similar logic is applied to all the if statements below

2020-12-06 00:17 UTC, issy approved these changes

2020-12-06 16:33 UTC, tigattack approved these changes

2020-12-06 17:18 UTC, merged